from engine.prompts.investigative_prompts import (
    PLANNER_SYSTEM_PROMPT,
    SYNTHESIS_SYSTEM_PROMPT,
    STATEMENT_SYSTEM_PROMPT,
    CROSS_CASE_SYSTEM_PROMPT,
    LAW_RETRIEVAL_SYSTEM_PROMPT
)

__all__ = [
    "PLANNER_SYSTEM_PROMPT",
    "SYNTHESIS_SYSTEM_PROMPT",
    "STATEMENT_SYSTEM_PROMPT",
    "CROSS_CASE_SYSTEM_PROMPT",
    "LAW_RETRIEVAL_SYSTEM_PROMPT"
]
