
"""
CrimeMind LangGraph Orchestrator.

Streams investigation events from the real agent engine.
No simulated investigation findings or synthetic fallback responses
are generated by this module.
"""

import json
import logging
import sys
import uuid

from datetime import datetime
from pathlib import Path
from typing import Any, AsyncGenerator, Dict, Optional

from sqlalchemy.orm import Session

from app.models.intelligence import AgentRun


logger = logging.getLogger(__name__)


# ============================================================
# 1. LOAD THE REAL AGENT ENGINE
# ============================================================

# Expected layout:
# CrimeMind/
# ├── agents/
# └── backend/
#     └── app/
#         └── services/
#             └── langgraph_service.py

AGENTS_PATH = (
    Path(__file__).resolve().parent.parent.parent.parent / "agents"
)

if str(AGENTS_PATH) not in sys.path:
    sys.path.insert(0, str(AGENTS_PATH))


HAS_AGENT_ENGINE = False
AGENT_ENGINE_IMPORT_ERROR = None

try:
    from engine.graph.master_graph import (
        stream_investigation as agent_stream_investigation,
        run_investigation as agent_run_investigation,
    )

    HAS_AGENT_ENGINE = True

    logger.info("CrimeMind real agent engine loaded successfully.")

except Exception as exc:
    AGENT_ENGINE_IMPORT_ERROR = exc

    logger.exception(
        "Failed to import the CrimeMind agent engine."
    )


# ============================================================
# 2. SHARED ORCHESTRATOR STATE
# ============================================================

class LangGraphState:
    """
    Shared state representation for an investigation request.

    The actual investigation graph maintains its own state.
    This class is retained for compatibility with other backend code.
    """

    def __init__(
        self,
        query: str,
        case_id: Optional[str] = None,
    ):
        self.query = query
        self.case_id = case_id
        self.plan = []
        self.agent_results = {}
        self.accumulated_findings = []
        self.sources = []
        self.final_synthesis = ""
        self.overall_confidence = 0.0


# ============================================================
# 3. LANGGRAPH ORCHESTRATOR
# ============================================================

class LangGraphOrchestrator:
    """
    Bridges the FastAPI backend to the real CrimeMind agent engine.

    Important:
    - Does not invent case records.
    - Does not create simulated agent findings.
    - Does not replace graph failures with canned responses.
    - Propagates investigation errors to the caller.
    """

    @classmethod
    async def run_pipeline_stream(
        cls,
        query: str,
        case_id: Optional[str] = None,
        db: Optional[Session] = None,
    ) -> AsyncGenerator[str, None]:
        """
        Execute the real investigation graph and stream its events
        as Server-Sent Events (SSE).
        """

        if not isinstance(query, str) or not query.strip():
            raise ValueError(
                "Investigation query must not be empty."
            )

        if not HAS_AGENT_ENGINE:
            raise RuntimeError(
                "The CrimeMind agent engine is unavailable. "
                "The investigation was not executed. "
                "No simulated results were generated."
            ) from AGENT_ENGINE_IMPORT_ERROR

        logger.info(
            "Starting investigation. case_id=%s",
            case_id,
        )

        try:
            async for event in agent_stream_investigation(
                query=query.strip(),
                case_id=case_id,
            ):
                yield cls._convert_to_sse(event)

            logger.info(
                "Investigation stream completed. case_id=%s",
                case_id,
            )

        except Exception:
            logger.exception(
                "The real investigation graph failed. "
                "case_id=%s. No synthetic fallback will be used.",
                case_id,
            )
            raise

    # ========================================================
    # 4. CONVERT GRAPH EVENTS TO SERVER-SENT EVENTS
    # ========================================================

    @staticmethod
    def _convert_to_sse(event: Any) -> str:
        """
        Convert an event from the agent engine into an SSE message.

        Supports:
        - Already formatted SSE strings
        - Dictionary events
        - Pydantic-style objects exposing model_dump()
        """

        if isinstance(event, str):
            # Preserve events that the graph has already formatted.
            if event.startswith("data:"):
                return event.rstrip() + "\n\n"

            # Plain-text events are forwarded as messages,
            # not interpreted as investigation findings.
            payload = {
                "event_type": "agent_update",
                "agent_name": "CrimeMind Agent Engine",
                "data": {
                    "message": event,
                },
                "timestamp": datetime.utcnow().isoformat(),
            }

            return (
                "data: "
                + json.dumps(payload, default=str)
                + "\n\n"
            )

        if hasattr(event, "model_dump"):
            event = event.model_dump()

        if isinstance(event, dict):
            return (
                "data: "
                + json.dumps(event, default=str)
                + "\n\n"
            )

        raise TypeError(
            "Unsupported event returned by the CrimeMind agent "
            f"engine: {type(event).__name__}"
        )

    # ========================================================
    # 5. SSE FORMATTER — RETAINED FOR COMPATIBILITY
    # ========================================================

    @staticmethod
    def _format_sse(
        event_type: str,
        agent_name: str,
        data: Dict[str, Any],
    ) -> str:
        """
        Format a structured event as Server-Sent Events.
        """

        payload = {
            "event_type": event_type,
            "agent_name": agent_name,
            "data": data,
            "timestamp": datetime.utcnow().isoformat(),
        }

        return (
            "data: "
            + json.dumps(payload, default=str)
            + "\n\n"
        )

    # ========================================================
    # 6. RECORD AGENT EXECUTION — RETAINED FOR COMPATIBILITY
    # ========================================================

    @staticmethod
    def _record_agent_run(
        db: Session,
        run_id: uuid.UUID,
        case_id: Optional[str],
        agent_name: str,
        task: str,
        status: str,
    ) -> None:
        """
        Record an agent execution using the existing AgentRun model.

        Database logging failures are logged and rolled back.
        They are not converted into investigation findings.
        """

        try:
            parsed_case_id = (
                uuid.UUID(str(case_id))
                if case_id
                else None
            )

            agent_run = AgentRun(
                run_id=run_id,
                case_id=parsed_case_id,
                agent_name=agent_name,
                task=task,
                status=status,
                started_at=datetime.utcnow(),
                completed_at=datetime.utcnow(),
            )

            db.add(agent_run)
            db.commit()

        except Exception:
            db.rollback()

            logger.exception(
                "Failed to record agent execution. "
                "agent_name=%s, case_id=%s",
                agent_name,
                case_id,
            )
