import logging
from typing import Dict, Any, List
from app.graph.state import InvestigativeState, AgentOutputItem, FindingItem, CitationItem
from app.utils.logger import AgentExecutionTimer
from app.utils.security_audit import SecurityAuditService

logger = logging.getLogger("CrimeMind.LawRetrievalAgent")


class LawRetrievalAgent:
    """
    Specialized agent retrieving statutory guidance, Fourth Amendment constraints,
    Title III wiretap standards, and evidence admissibility policies.
    Guarantees: NEVER invents or hallucinates statutory codes.
    """
    NAME = "Law Retrieval Agent"

    # Curated knowledge base of statutory and constitutional authorities
    APPROVED_LEGAL_REPOSITORY = [
        {
            "statute_id": "STAT-CONST-4TH",
            "jurisdiction": "United States Federal / Constitutional",
            "source": "U.S. Constitution, Amendment IV",
            "section": "Unreasonable Searches and Seizures / Warrant Clause",
            "date_version": "1791 (Ratified), modern Supreme Court doctrine (Carpenter v. United States, 2018)",
            "summary": "Acquisition of historical cell-site location information (CSLI) spanning >6 days requires a probable cause warrant supported by judicial oath."
        },
        {
            "statute_id": "STAT-FED-TITLE-III",
            "jurisdiction": "United States Federal Statutory",
            "source": "18 U.S.C. §§ 2510-2522 (Title III Wiretap Act)",
            "section": "Interception of Wire, Oral, or Electronic Communications",
            "date_version": "Public Law 90-351, as amended by ECPA",
            "summary": "Real-time intercept of voice communications requires prior judicial authorization with showing of probable cause, minimization procedures, and exhaustion of normal investigative techniques."
        },
        {
            "statute_id": "STAT-FRE-901",
            "jurisdiction": "Federal Rules of Evidence",
            "source": "Fed. R. Evid. 901 & 902",
            "section": "Authenticating or Identifying Evidence / Self-Authenticating Records",
            "date_version": "December 1, 2017 amendments",
            "summary": "Electronic records generated by digital processes require proof that the system produces accurate results (certified digital hash signatures satisfy self-authentication under Rule 902(13))."
        }
    ]

    @classmethod
    async def execute(cls, state: InvestigativeState) -> InvestigativeState:
        with AgentExecutionTimer(cls.NAME, "Retrieving statutory & procedural legal authorities") as timer:
            try:
                query_lower = state.query.lower()
                retrieved_statutes = []

                # Select relevant statutory authorities based on investigative components
                if any(w in query_lower for w in ["call", "phone", "audio", "wiretap", "intercept"]):
                    retrieved_statutes.append(cls.APPROVED_LEGAL_REPOSITORY[1])
                if any(w in query_lower for w in ["location", "cell", "tower", "ping", "cctv", "tracking"]):
                    retrieved_statutes.append(cls.APPROVED_LEGAL_REPOSITORY[0])
                if any(w in query_lower for w in ["evidence", "file", "custody", "hash", "tamper"]):
                    retrieved_statutes.append(cls.APPROVED_LEGAL_REPOSITORY[2])

                # If generic inquiry, provide core admissibility framework
                if not retrieved_statutes:
                    retrieved_statutes = [cls.APPROVED_LEGAL_REPOSITORY[0], cls.APPROVED_LEGAL_REPOSITORY[2]]

                findings_list = []
                for st in retrieved_statutes:
                    summary_line = (
                        f"[{st['jurisdiction']}] {st['source']} - {st['section']}: {st['summary']}"
                    )
                    findings_list.append(summary_line)

                    state.add_finding(FindingItem(
                        category="OBSERVED FACT",
                        title=f"Legal Compliance Standard: {st['source']}",
                        finding=f"Governing Legal Framework: {st['summary']}",
                        supporting_evidence_ids=[st["statute_id"]],
                        confidence=1.0,
                        status="APPROVED_LEGAL_FRAMEWORK"
                    ))

                    state.add_citation(CitationItem(
                        citation_id=f"cit-law-{st['statute_id']}",
                        source_type="STATUTE",
                        reference_id=st["statute_id"],
                        summary=f"{st['source']} ({st['jurisdiction']})"
                    ))

                output = AgentOutputItem(
                    agent_name=cls.NAME,
                    task="Legal admissibility & statutory authority retrieval",
                    status="completed",
                    execution_time_ms=timer.duration_ms,
                    confidence=1.0,
                    findings=findings_list,
                    data={"statutes_retrieved": len(retrieved_statutes)}
                )
                state.add_agent_output(output)

                SecurityAuditService.record_agent_run(
                    case_id=state.case_id,
                    agent_name=cls.NAME,
                    task="Legal Policy Retrieval",
                    status="completed",
                    duration_ms=timer.duration_ms,
                    confidence=1.0,
                    output_summary={"statutes_count": len(retrieved_statutes)}
                )

            except Exception as e:
                logger.error(f"Law Retrieval Agent error: {e}", exc_info=True)
                state.add_error(cls.NAME, str(e))
                state.add_agent_output(AgentOutputItem(
                    agent_name=cls.NAME,
                    task="Legal Policy Retrieval",
                    status="failed",
                    execution_time_ms=timer.duration_ms,
                    confidence=0.0,
                    errors=str(e)
                ))

        return state
