// ============================================================================
// CrimeMind High-Fidelity Synthetic Intelligence Store
// File: mockData.ts
// Fully implements the 5 interconnected demonstration scenarios matching
// the PostgreSQL schema and view contracts.
// ============================================================================

import {
  Case,
  Person,
  Incident,
  Evidence,
  Vehicle,
  CCTVCamera,
  CCTVDetection,
  LocationRecord,
  CallRecord,
  TransactionRecord,
  TimelineEvent,
  AgentRun,
  AIFinding,
  InvestigationNote,
  Alert,
  GraphData
} from '../types';

// ----------------------------------------------------------------------------
// 1. LOCATIONS
// ----------------------------------------------------------------------------
export const initialLocations: LocationRecord[] = [
  {
    location_id: 'loc-001',
    name: 'Metropolis First National Bank & Vault',
    address: '450 Vanderbilt Way',
    city: 'Metropolis Central',
    area: 'Downtown Commercial District',
    postal_code: 'MC-10001',
    latitude: 40.7589,
    longitude: -73.9851,
    location_type: 'atm_bank',
    risk_level: 'critical',
    total_incidents: 4,
    total_cctv_detections: 1420,
    total_person_sightings: 890,
  },
  {
    location_id: 'loc-002',
    name: 'Waterfront Terminal 4 Container Yard',
    address: 'Pier 42 Access Rd',
    city: 'Metropolis Central',
    area: 'Industrial Waterfront & Port',
    postal_code: 'MC-10042',
    latitude: 40.7028,
    longitude: -74.0150,
    location_type: 'port_marina',
    risk_level: 'high',
    total_incidents: 6,
    total_cctv_detections: 2310,
    total_person_sightings: 1140,
  },
  {
    location_id: 'loc-003',
    name: 'Belvedere Luxury Residential Estates',
    address: '88 Beacon Ridge',
    city: 'Metropolis Central',
    area: 'Northshore Heights',
    postal_code: 'MC-10088',
    latitude: 40.8120,
    longitude: -73.9520,
    location_type: 'residential',
    risk_level: 'high',
    total_incidents: 8,
    total_cctv_detections: 1890,
    total_person_sightings: 640,
  },
  {
    location_id: 'loc-004',
    name: 'Grand Central Diamond & Watch Exchange',
    address: '12 Lexington Ave',
    city: 'Metropolis Central',
    area: 'Midtown Financial Plaza',
    postal_code: 'MC-10012',
    latitude: 40.7505,
    longitude: -73.9772,
    location_type: 'commercial',
    risk_level: 'high',
    total_incidents: 3,
    total_cctv_detections: 3200,
    total_person_sightings: 2100,
  },
  {
    location_id: 'loc-005',
    name: 'Apex Nightclub & Private Lounge',
    address: '204 Foundry Street',
    city: 'Metropolis Central',
    area: 'Eastside Arts Corridor',
    postal_code: 'MC-10020',
    latitude: 40.7250,
    longitude: -73.9910,
    location_type: 'entertainment_venue',
    risk_level: 'critical',
    total_incidents: 5,
    total_cctv_detections: 2840,
    total_person_sightings: 1950,
  },
  {
    location_id: 'loc-006',
    name: 'Silver Lake Industrial Logistics Depot',
    address: '910 Commerce Expressway',
    city: 'Metropolis Central',
    area: 'South Bay Logistics Hub',
    postal_code: 'MC-10091',
    latitude: 40.6912,
    longitude: -74.0321,
    location_type: 'warehouse',
    risk_level: 'moderate',
    total_incidents: 2,
    total_cctv_detections: 980,
    total_person_sightings: 430,
  }
];

// ----------------------------------------------------------------------------
// 2. PERSONS (With 5 Key Demo Anchors)
// ----------------------------------------------------------------------------
export const initialPersons: Person[] = [
  // Scenario 1: Viper (Marcus Vance)
  {
    person_id: 'per-001',
    first_name: 'Marcus',
    last_name: 'Vance',
    full_name: 'Marcus Vance',
    aliases: ['Viper', 'The Fence'],
    date_of_birth: '1980-04-12',
    age: 44,
    gender: 'male',
    national_id_synthetic: 'SYN-NAT-MV89421',
    occupation: 'Pawn Shop Operator & Antiquities Dealer',
    description: 'Suspected fencing coordinator and organizer behind high-value residential estate break-ins.',
    phone_numbers: ['+1-555-882-1902'],
    email_addresses: ['vance.pawn@synthetic-mail.net'],
    addresses: ['742 St. Marks Place, Metropolis Central'],
    risk_level: 'extreme',
    risk_indicators: ['prior_burglary_conviction', 'weapons_affinity', 'high_value_fencing', 'money_laundering_suspect'],
    notes: 'Surveillance indicates frequent contact with locksmith Julian Drake and encrypted communications with broker Evelyn Reed.',
    total_cases_associated: 8,
    cases_as_suspect: 8,
    registered_vehicles_count: 1,
    cctv_detections_count: 42,
    total_calls_recorded: 128,
    total_transactions_recorded: 64,
    direct_network_size: 14,
    created_at: '2023-01-10T10:00:00Z',
    updated_at: '2024-08-15T14:30:00Z',
  },
  // Scenario 1: Ghost (Julian Drake)
  {
    person_id: 'per-002',
    first_name: 'Julian',
    last_name: 'Drake',
    full_name: 'Julian Drake',
    aliases: ['Ghost', 'The Keymaster'],
    date_of_birth: '1986-09-24',
    age: 38,
    gender: 'male',
    national_id_synthetic: 'SYN-NAT-JD34019',
    occupation: 'Commercial Locksmith & Security Installer',
    description: 'Expert safecracker and electronic security bypass specialist for the Midnight Syndicate.',
    phone_numbers: ['+1-555-412-9901'],
    email_addresses: ['drake.locks@synthetic-mail.net'],
    addresses: ['112 Highland Blvd, Metropolis Central'],
    risk_level: 'high',
    risk_indicators: ['master_locksmith_bypass', 'alarm_suppression_expert', 'counter_surveillance'],
    notes: 'Possesses optical laser drill equipment matching incisions recorded in Case CASE-2023-0100 through CASE-2024-0107.',
    total_cases_associated: 8,
    cases_as_suspect: 8,
    registered_vehicles_count: 1,
    cctv_detections_count: 36,
    total_calls_recorded: 94,
    total_transactions_recorded: 32,
    direct_network_size: 9,
    created_at: '2023-01-12T11:00:00Z',
    updated_at: '2024-08-10T09:20:00Z',
  },
  // Scenario 2: Damian Cross (Apex)
  {
    person_id: 'per-003',
    first_name: 'Damian',
    last_name: 'Cross',
    full_name: 'Damian Cross',
    aliases: ['Apex'],
    date_of_birth: '1991-03-15',
    age: 33,
    gender: 'male',
    national_id_synthetic: 'SYN-NAT-DC10294',
    occupation: 'Nightclub Security Lead',
    description: 'Driver and registered owner of Dark Gray 2021 Dodge Charger (SYN-7X91).',
    phone_numbers: ['+1-555-667-2019'],
    email_addresses: ['damian.cross@synthetic-mail.net'],
    addresses: ['89 Quarry Lane, Metropolis Central'],
    risk_level: 'high',
    risk_indicators: ['getaway_driver', 'registered_owner_charger', 'evasion_tactics'],
    notes: 'Vehicle captured departing scene of 4 armed commercial robberies.',
    total_cases_associated: 4,
    cases_as_suspect: 4,
    registered_vehicles_count: 1,
    cctv_detections_count: 58,
    total_calls_recorded: 112,
    total_transactions_recorded: 28,
    direct_network_size: 11,
    created_at: '2024-01-05T08:00:00Z',
    updated_at: '2024-08-20T16:45:00Z',
  },
  // Scenario 3: Evelyn Reed (Cipher)
  {
    person_id: 'per-004',
    first_name: 'Evelyn',
    last_name: 'Reed',
    full_name: 'Evelyn Reed',
    aliases: ['Cipher', 'The Broker'],
    date_of_birth: '1983-11-04',
    age: 41,
    gender: 'female',
    national_id_synthetic: 'SYN-NAT-ER99401',
    occupation: 'Independent Logistics Consultant',
    description: 'Central communications nexus linking disparate criminal syndicates without physical presence.',
    phone_numbers: ['+1-555-019-4821'],
    email_addresses: ['evelyn.reed@synthetic-mail.net'],
    addresses: ['340 Sunset Parkway, Penthouse 14, Metropolis Central'],
    risk_level: 'extreme',
    risk_indicators: ['clandestine_communications', 'multi_syndicate_facilitator', 'burner_nexus_hub'],
    notes: 'Logs reveal encrypted calls with Marcus Vance, Damian Cross, Trevor Bennett, and Viktor Orlov prior to major incidents.',
    total_cases_associated: 6,
    cases_as_suspect: 2,
    registered_vehicles_count: 2,
    cctv_detections_count: 24,
    total_calls_recorded: 480,
    total_transactions_recorded: 145,
    direct_network_size: 26,
    created_at: '2023-05-18T14:00:00Z',
    updated_at: '2024-08-28T11:15:00Z',
  },
  // Scenario 4: Trevor Bennett (Spike)
  {
    person_id: 'per-005',
    first_name: 'Trevor',
    last_name: 'Bennett',
    full_name: 'Trevor Bennett',
    aliases: ['Spike'],
    date_of_birth: '1997-08-20',
    age: 27,
    gender: 'male',
    national_id_synthetic: 'SYN-NAT-TB77102',
    occupation: 'Scrap Metal Sorter',
    description: 'Safe penetration operative implicated in First National Bank branch breach.',
    phone_numbers: ['+1-555-334-9182'],
    email_addresses: ['t.bennett@synthetic-mail.net'],
    addresses: ['52 Atlantic Ave, Metropolis Central'],
    risk_level: 'high',
    risk_indicators: ['rapid_withdrawal_mule', 'safe_breach_operative', 'heavy_tooling'],
    notes: 'Received $25,000 wire transfer 3.5 hours prior to night vault infiltration attempt.',
    total_cases_associated: 2,
    cases_as_suspect: 2,
    registered_vehicles_count: 0,
    cctv_detections_count: 19,
    total_calls_recorded: 44,
    total_transactions_recorded: 18,
    direct_network_size: 6,
    created_at: '2024-04-10T09:30:00Z',
    updated_at: '2024-08-22T17:00:00Z',
  },
  // Scenario 5: Viktor Orlov (Old Fox)
  {
    person_id: 'per-006',
    first_name: 'Viktor',
    last_name: 'Orlov',
    full_name: 'Viktor Orlov',
    aliases: ['Old Fox'],
    date_of_birth: '1966-02-14',
    age: 58,
    gender: 'male',
    national_id_synthetic: 'SYN-NAT-VO44901',
    occupation: 'Freight Terminal Overseer',
    description: 'Convicted in 2021 freight hijacking (CASE-2021-0044); resurfaced in 2024 Terminal 4 container theft.',
    phone_numbers: ['+1-555-901-7723'],
    email_addresses: ['orlov.freight@synthetic-mail.net'],
    addresses: ['410 Pier Rd, Metropolis Central'],
    risk_level: 'extreme',
    risk_indicators: ['historical_convict_2021', 'recidivist_syndicate_boss', 'interstate_smuggler'],
    notes: 'Operates registered Black 2018 Ford Explorer (SYN-4K82). High probability of active fencing network.',
    total_cases_associated: 3,
    cases_as_suspect: 3,
    registered_vehicles_count: 1,
    cctv_detections_count: 67,
    total_calls_recorded: 160,
    total_transactions_recorded: 88,
    direct_network_size: 19,
    created_at: '2021-01-20T12:00:00Z',
    updated_at: '2024-08-26T18:00:00Z',
  }
];

// ----------------------------------------------------------------------------
// 3. VEHICLES
// ----------------------------------------------------------------------------
export const initialVehicles: Vehicle[] = [
  // Scenario 2: Dodge Charger
  {
    vehicle_id: 'veh-001',
    registration_number: 'SYN-7X91',
    vin: '1SYN2DGE8912301X4',
    vehicle_type: 'sedan',
    make: 'Dodge',
    model: 'Charger',
    year: 2021,
    color: 'Dark Gray',
    owner_person_id: 'per-003',
    owner_name: 'Damian Cross',
    stolen_status: false,
    notes: 'Flagged getaway vehicle: Sighted within 20 mins before and 15 mins after 4 armed commercial robberies.',
    metadata: { tinted_windows: true, scenario: 'SCENARIO_2' },
  },
  // Scenario 5: Ford Explorer
  {
    vehicle_id: 'veh-002',
    registration_number: 'SYN-4K82',
    vin: '1SYN1FRD4892019Y9',
    vehicle_type: 'suv',
    make: 'Ford',
    model: 'Explorer',
    year: 2018,
    color: 'Black',
    owner_person_id: 'per-006',
    owner_name: 'Viktor Orlov',
    stolen_status: false,
    notes: 'Linked to 2021 freight theft CASE-2021-0044; recently spotted near Terminal 4 container breach in 2024.',
    metadata: { cross_case_anchor: true, scenario: 'SCENARIO_5' },
  },
  {
    vehicle_id: 'veh-003',
    registration_number: 'SYN-9B14',
    vin: '1SYN3CHV7710294Z1',
    vehicle_type: 'van',
    make: 'Chevrolet',
    model: 'Express',
    year: 2019,
    color: 'White',
    owner_person_id: 'per-002',
    owner_name: 'Julian Drake',
    stolen_status: false,
    notes: 'Commercial locksmith utility van carrying key cutting tooling.',
  }
];

// ----------------------------------------------------------------------------
// 4. CASES
// ----------------------------------------------------------------------------
export const initialCases: Case[] = [
  // Scenario 1 Cases: Burglary Network
  {
    case_id: 'case-001',
    case_number: 'CASE-2024-0106',
    title: 'Midnight Syndicate: Belvedere Estate Burglary #7',
    description: 'High-value residential break-in in Northshore Heights. Laser-severed fiber alarm cables, side window forced entry, $240,000 jewelry taken.',
    status: 'under_investigation',
    priority: 'high',
    crime_type: 'Aggravated Burglary',
    investigating_officer_id: 'usr-101',
    investigating_officer_name: 'Det. Sarah Vance',
    primary_location_id: 'loc-003',
    primary_location_name: 'Belvedere Luxury Residential Estates',
    primary_city: 'Metropolis Central',
    opened_at: '2024-06-18T03:15:00Z',
    suspect_count: 3,
    victim_count: 2,
    evidence_count: 14,
    ai_finding_count: 4,
    unverified_ai_finding_count: 2,
    latest_event_time: '2024-08-28T09:40:00Z',
    created_at: '2024-06-18T03:15:00Z',
    updated_at: '2024-08-28T10:00:00Z',
    metadata: { scenario: 'SCENARIO_1_BURGLARY_NETWORK' },
  },
  // Scenario 2 Cases: Phantom Charger
  {
    case_id: 'case-002',
    case_number: 'CASE-2024-1100',
    title: 'Midtown Jewelry Exchange Armed Robbery',
    description: 'Rapid 3-minute armed robbery of boutique watch counter. Dark Gray Dodge Charger (SYN-7X91) logged departing at high velocity.',
    status: 'under_investigation',
    priority: 'critical',
    crime_type: 'Commercial Robbery',
    investigating_officer_id: 'usr-102',
    investigating_officer_name: 'Lt. James Miller',
    primary_location_id: 'loc-004',
    primary_location_name: 'Grand Central Diamond & Watch Exchange',
    primary_city: 'Metropolis Central',
    opened_at: '2024-05-10T21:30:00Z',
    suspect_count: 2,
    victim_count: 4,
    evidence_count: 18,
    ai_finding_count: 5,
    unverified_ai_finding_count: 1,
    latest_event_time: '2024-08-25T14:20:00Z',
    created_at: '2024-05-10T21:30:00Z',
    updated_at: '2024-08-25T15:00:00Z',
    metadata: { scenario: 'SCENARIO_2_VEHICLE_NEAR_INCIDENTS' },
  },
  // Scenario 4 Case: Bank Vault Breach
  {
    case_id: 'case-003',
    case_number: 'CASE-2024-0771',
    title: 'First National Bank Night Vault Infiltration',
    description: 'Attempted basement vault breach following $25,000 illicit funding transfer. Core drill bits and electronic jammer left on scene.',
    status: 'under_investigation',
    priority: 'critical',
    crime_type: 'Armed Bank Robbery',
    investigating_officer_id: 'usr-101',
    investigating_officer_name: 'Det. Sarah Vance',
    primary_location_id: 'loc-001',
    primary_location_name: 'Metropolis First National Bank & Vault',
    primary_city: 'Metropolis Central',
    opened_at: '2024-05-14T02:45:00Z',
    suspect_count: 2,
    victim_count: 1,
    evidence_count: 22,
    ai_finding_count: 6,
    unverified_ai_finding_count: 3,
    latest_event_time: '2024-08-29T11:00:00Z',
    created_at: '2024-05-14T02:45:00Z',
    updated_at: '2024-08-29T11:30:00Z',
    metadata: { scenario: 'SCENARIO_4_FINANCIAL_TO_PHYSICAL_CRIME' },
  },
  // Scenario 5 Active Case: Terminal 4 Breach
  {
    case_id: 'case-004',
    case_number: 'CASE-2024-2390',
    title: 'Waterfront Terminal 4 Container Freight Diversion',
    description: 'Commercial shipping container breach at Port Terminal 4. High-value electronics diverted using false customs manifest.',
    status: 'under_investigation',
    priority: 'high',
    crime_type: 'Organized Cargo Theft',
    investigating_officer_id: 'usr-103',
    investigating_officer_name: 'Capt. Robert Chen',
    primary_location_id: 'loc-002',
    primary_location_name: 'Waterfront Terminal 4 Container Yard',
    primary_city: 'Metropolis Central',
    opened_at: '2024-07-18T05:00:00Z',
    suspect_count: 2,
    victim_count: 3,
    evidence_count: 11,
    ai_finding_count: 3,
    unverified_ai_finding_count: 1,
    latest_event_time: '2024-08-27T16:15:00Z',
    created_at: '2024-07-18T05:00:00Z',
    updated_at: '2024-08-27T17:00:00Z',
    metadata: { scenario: 'SCENARIO_5_CROSS_CASE_HISTORICAL_LINK' },
  },
  // Scenario 5 Historical Case: 2021 Ironclad (Closed)
  {
    case_id: 'case-005',
    case_number: 'CASE-2021-0044',
    title: 'Operation Ironclad: Harbor Logistics Freight Hijacking',
    description: 'Historical investigation resulting in conviction of Viktor Orlov for armed hijacking of logistics convoy. Case successfully closed with full asset recovery.',
    status: 'closed',
    priority: 'high',
    crime_type: 'Organized Cargo Theft',
    investigating_officer_id: 'usr-103',
    investigating_officer_name: 'Capt. Robert Chen',
    primary_location_id: 'loc-002',
    primary_location_name: 'Waterfront Terminal 4 Container Yard',
    primary_city: 'Metropolis Central',
    opened_at: '2021-03-10T12:00:00Z',
    closed_at: '2021-11-20T17:00:00Z',
    suspect_count: 4,
    victim_count: 2,
    evidence_count: 28,
    ai_finding_count: 2,
    unverified_ai_finding_count: 0,
    latest_event_time: '2021-11-20T17:00:00Z',
    created_at: '2021-03-10T12:00:00Z',
    updated_at: '2021-11-20T17:00:00Z',
    metadata: { scenario: 'SCENARIO_5_HISTORICAL_CONVICTION' },
  },
  // Active Open Case 1: Harbor Weapons & Fentanyl Pipeline (Open)
  {
    case_id: 'case-006',
    case_number: 'CASE-2024-4019',
    title: 'Harbor District Weapons & Synthetic Narcotics Pipeline',
    description: 'Active open case initiated following confidential informant tip regarding maritime shipment of military-grade optics and precursors at Pier 42.',
    status: 'open',
    priority: 'critical',
    crime_type: 'Contraband Trafficking',
    investigating_officer_id: 'usr-101',
    investigating_officer_name: 'Det. Sarah Vance',
    primary_location_id: 'loc-002',
    primary_location_name: 'Waterfront Terminal 4 Container Yard',
    primary_city: 'Metropolis Central',
    opened_at: '2024-08-20T08:00:00Z',
    suspect_count: 3,
    victim_count: 0,
    evidence_count: 8,
    ai_finding_count: 3,
    unverified_ai_finding_count: 2,
    latest_event_time: '2024-08-29T14:10:00Z',
    created_at: '2024-08-20T08:00:00Z',
    updated_at: '2024-08-29T15:00:00Z',
    metadata: { scenario: 'SCENARIO_6_ACTIVE_OPEN_PIPELINE' },
  },
  // Active Open Case 2: Cyber Financial Intrusion (Open)
  {
    case_id: 'case-007',
    case_number: 'CASE-2024-8831',
    title: 'Municipal Ledger Cryptolocker Extortion Breach',
    description: 'Newly opened probe into decentralized wire diversion spoofing city contractor escrow accounts. Linked to encrypted burner communications.',
    status: 'open',
    priority: 'high',
    crime_type: 'Cyber Extortion & Wire Fraud',
    investigating_officer_id: 'usr-102',
    investigating_officer_name: 'Lt. James Miller',
    primary_location_id: 'loc-001',
    primary_location_name: 'Metropolis First National Bank & Vault',
    primary_city: 'Metropolis Central',
    opened_at: '2024-08-26T11:45:00Z',
    suspect_count: 1,
    victim_count: 5,
    evidence_count: 6,
    ai_finding_count: 2,
    unverified_ai_finding_count: 1,
    latest_event_time: '2024-08-29T09:30:00Z',
    created_at: '2024-08-26T11:45:00Z',
    updated_at: '2024-08-29T10:00:00Z',
    metadata: { scenario: 'SCENARIO_7_CYBER_EXTORTION' },
  },
  // Cold / Reopened Case 1: Belvedere Vault 2023 (Reopened)
  {
    case_id: 'case-008',
    case_number: 'CASE-2023-0100',
    title: 'Belvedere Diamond Vault Breach #1 (Reopened Lead)',
    description: 'Cold case reopened on August 2024 after CSU spectrographic laser tool-mark correlation linked original incision with seized Julian Drake apparatus.',
    status: 'reopened',
    priority: 'critical',
    crime_type: 'Aggravated Burglary',
    investigating_officer_id: 'usr-101',
    investigating_officer_name: 'Det. Sarah Vance',
    primary_location_id: 'loc-003',
    primary_location_name: 'Belvedere Luxury Residential Estates',
    primary_city: 'Metropolis Central',
    opened_at: '2023-01-10T10:00:00Z',
    suspect_count: 2,
    victim_count: 1,
    evidence_count: 16,
    ai_finding_count: 4,
    unverified_ai_finding_count: 1,
    latest_event_time: '2024-08-28T18:00:00Z',
    created_at: '2023-01-10T10:00:00Z',
    updated_at: '2024-08-28T18:30:00Z',
    metadata: { scenario: 'SCENARIO_8_REOPENED_COLD_CASE' },
  },
  // Historical Closed Case 2: Armored Truck Ambush (Closed)
  {
    case_id: 'case-009',
    case_number: 'CASE-2022-0912',
    title: 'Metro Transit Armored Truck Highway Ambush',
    description: 'Comprehensive armed robbery prosecution closed with guilty plea. All cash pallets accounted for and stored in state depository vault.',
    status: 'closed',
    priority: 'critical',
    crime_type: 'Armed Robbery',
    investigating_officer_id: 'usr-103',
    investigating_officer_name: 'Capt. Robert Chen',
    primary_location_id: 'loc-004',
    primary_location_name: 'Grand Central Diamond & Watch Exchange',
    primary_city: 'Metropolis Central',
    opened_at: '2022-09-12T14:00:00Z',
    closed_at: '2023-04-15T10:00:00Z',
    suspect_count: 3,
    victim_count: 2,
    evidence_count: 24,
    ai_finding_count: 1,
    unverified_ai_finding_count: 0,
    latest_event_time: '2023-04-15T10:00:00Z',
    created_at: '2022-09-12T14:00:00Z',
    updated_at: '2023-04-15T10:00:00Z',
    metadata: { scenario: 'SCENARIO_9_CLOSED_AMBUSH' },
  }
];

// ----------------------------------------------------------------------------
// 5. CCTV DETECTIONS
// ----------------------------------------------------------------------------
export const initialCCTVDetections: CCTVDetection[] = [
  {
    detection_id: 'det-001',
    camera_id: 'cam-014',
    camera_code: 'CAM-DT-014',
    camera_name: 'Midtown 5th & Lexington Traffic South',
    location_name: 'Downtown Commercial District',
    detected_at: '2024-05-10T21:12:00Z',
    vehicle_id: 'veh-001',
    vehicle_plate: 'SYN-7X91',
    detected_object: 'license_plate',
    confidence: 0.965,
    image_reference: '/surveillance/captures/cam014_plate_syn7x91.jpg',
    bounding_box: { x: 0.32, y: 0.45, width: 0.22, height: 0.18 },
    event_metadata: { ocr_plate: 'SYN-7X91', speed_kmh: 48, heading: 'Eastbound' },
    verification_status: 'RAW_DATA',
  },
  {
    detection_id: 'det-002',
    camera_id: 'cam-014',
    camera_code: 'CAM-DT-014',
    camera_name: 'Midtown 5th & Lexington Traffic South',
    location_name: 'Downtown Commercial District',
    detected_at: '2024-05-10T21:45:00Z',
    vehicle_id: 'veh-001',
    vehicle_plate: 'SYN-7X91',
    detected_object: 'vehicle',
    confidence: 0.942,
    image_reference: '/surveillance/captures/cam014_vehicle_syn7x91.jpg',
    bounding_box: { x: 0.15, y: 0.28, width: 0.48, height: 0.35 },
    event_metadata: { ocr_plate: 'SYN-7X91', speed_kmh: 92, heading: 'Northbound' },
    verification_status: 'RAW_DATA',
  },
  {
    detection_id: 'det-003',
    camera_id: 'cam-003',
    camera_code: 'CAM-BK-003',
    camera_name: 'First National Bank Rear Alleyway',
    location_name: 'Metropolis First National Bank & Vault',
    detected_at: '2024-05-14T02:00:00Z',
    person_id: 'per-005',
    person_name: 'Trevor Bennett',
    detected_object: 'face',
    confidence: 0.978,
    image_reference: '/surveillance/captures/cam003_face_trevor.jpg',
    bounding_box: { x: 0.41, y: 0.22, width: 0.16, height: 0.21 },
    event_metadata: { match_target: 'Trevor Bennett', facial_landmarks: 68 },
    verification_status: 'AI_FINDING',
  },
  {
    detection_id: 'det-004',
    camera_id: 'cam-028',
    camera_code: 'CAM-PT-028',
    camera_name: 'Terminal 4 Gate 8 Ingress',
    location_name: 'Waterfront Terminal 4 Container Yard',
    detected_at: '2024-07-17T23:40:00Z',
    vehicle_id: 'veh-002',
    vehicle_plate: 'SYN-4K82',
    detected_object: 'vehicle',
    confidence: 0.981,
    image_reference: '/surveillance/captures/cam028_explorer.jpg',
    bounding_box: { x: 0.25, y: 0.35, width: 0.45, height: 0.38 },
    event_metadata: { ocr_plate: 'SYN-4K82', registered_owner: 'Viktor Orlov' },
    verification_status: 'RAW_DATA',
  }
];

// ----------------------------------------------------------------------------
// 6. CCTV CAMERAS
// ----------------------------------------------------------------------------
export const initialCCTVCameras: CCTVCamera[] = [
  {
    camera_id: 'cam-014',
    location_id: 'loc-004',
    camera_name: 'Midtown 5th & Lexington Traffic South',
    camera_code: 'CAM-DT-014',
    source: 'traffic_police',
    resolution: '4K',
    field_of_view: 'southbound_expressway',
    status: 'active',
    location_name: 'Downtown Commercial District',
    city: 'Metropolis Central',
    area: 'Downtown Commercial District',
    latitude: 40.7505,
    longitude: -73.9772,
  },
  {
    camera_id: 'cam-003',
    location_id: 'loc-001',
    camera_name: 'First National Bank Rear Alleyway',
    camera_code: 'CAM-BK-003',
    source: 'private_commercial',
    resolution: '1080p',
    field_of_view: 'vault_emergency_egress',
    status: 'active',
    location_name: 'Metropolis First National Bank & Vault',
    city: 'Metropolis Central',
    area: 'Downtown Commercial District',
    latitude: 40.7589,
    longitude: -73.9851,
  },
  {
    camera_id: 'cam-028',
    location_id: 'loc-002',
    camera_name: 'Terminal 4 Gate 8 Ingress',
    camera_code: 'CAM-PT-028',
    source: 'municipal_surveillance',
    resolution: '1080p',
    field_of_view: 'terminal_gate_scale',
    status: 'active',
    location_name: 'Waterfront Terminal 4 Container Yard',
    city: 'Metropolis Central',
    area: 'Industrial Waterfront & Port',
    latitude: 40.7028,
    longitude: -74.0150,
  }
];

// ----------------------------------------------------------------------------
// 7. EVIDENCE ITEMS (Multimodal Vault)
// ----------------------------------------------------------------------------
export const initialEvidence: Evidence[] = [
  {
    evidence_id: 'evd-001',
    case_id: 'case-001',
    case_number: 'CASE-2024-0106',
    evidence_number: 'EVD-2024-00192',
    evidence_type: 'forensic_records',
    title: 'Laser Cut Fiber Optic Alarm Lead Fragments',
    description: 'Clean circular incision through hardened conduit casing, matching thermal laser cutter.',
    source: 'Crime Scene Unit Lab',
    collected_at: '2024-06-18T06:30:00Z',
    file_path: 's3://crimemind-vault/cases/CASE-2024-0106/evd-00192.pdf',
    hash: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
    confidence: 0.98,
    ai_analysis_status: 'completed',
    ai_summary: 'Tool marks match seizure records from Julian Drake 2019 inquiry with 96.4% confidence.',
    chain_of_custody: [
      { action: 'secured', officer_name: 'Inv. Ramos', timestamp: '2024-06-18T06:30:00Z', facility: 'CSU Field Van' },
      { action: 'logged', officer_name: 'Det. Sarah Vance', timestamp: '2024-06-18T09:00:00Z', facility: 'Central Vault' }
    ]
  },
  {
    evidence_id: 'evd-002',
    case_id: 'case-002',
    case_number: 'CASE-2024-1100',
    evidence_number: 'EVD-2024-00341',
    evidence_type: 'cctv_records',
    title: 'CCTV Surveillance Capture - Dodge Charger Sighting',
    description: 'High definition capture of Dark Gray Charger accelerating away with obscured rear plate.',
    source: 'Municipal Traffic Cam 14',
    collected_at: '2024-05-10T22:00:00Z',
    file_path: 's3://crimemind-vault/cases/CASE-2024-1100/evd-00341.mp4',
    hash: 'a591a6d40bf420404a011733cfb7b190d62c65bf0bcda32b57b277d9ad9f146e',
    confidence: 0.94,
    ai_analysis_status: 'completed',
    ai_summary: 'Super-resolution OCR reconstruction reveals license registration SYN-7X91 registered to Damian Cross.',
    chain_of_custody: [
      { action: 'digital_export', officer_name: 'Analyst K. Gomez', timestamp: '2024-05-10T22:00:00Z', facility: 'Cyber Forensics Unit' }
    ]
  },
  {
    evidence_id: 'evd-003',
    case_id: 'case-003',
    case_number: 'CASE-2024-0771',
    evidence_number: 'EVD-2024-00512',
    evidence_type: 'transaction_records',
    title: '$25,000 Offshore Wire Transfer Record',
    description: 'Wire originating from Cayman entity Global Escrow LLC credited to Trevor Bennett personal account.',
    source: 'Financial Crimes Enforcement Network (FinCEN)',
    collected_at: '2024-05-14T08:00:00Z',
    file_path: 's3://crimemind-vault/cases/CASE-2024-0771/evd-00512.json',
    hash: 'b45cffe084dd3d20d928bee85e7b0f21',
    confidence: 1.0,
    ai_analysis_status: 'flagged',
    ai_summary: 'Correlated with phone call from Evelyn Reed 40 minutes prior to wire initiation.',
    chain_of_custody: [
      { action: 'subpoena_received', officer_name: 'Det. Sarah Vance', timestamp: '2024-05-14T08:00:00Z', facility: 'Financial Crimes Bureau' }
    ]
  },
  {
    evidence_id: 'evd-004',
    case_id: 'case-001',
    case_number: 'CASE-2024-0106',
    evidence_number: 'EVD-2024-00781',
    evidence_type: 'images',
    title: 'High-Resolution Macro Photo of Forced Side Window Frame',
    description: 'CSU photographic evidence showing specialized titanium crowbar pry marks and micro-paint transfer.',
    source: 'Crime Scene Unit Photography Team',
    collected_at: '2024-06-18T05:45:00Z',
    file_path: 's3://crimemind-vault/cases/CASE-2024-0106/window_macro_csu.jpg',
    hash: 'c19284fa98019481adabde991048472910471928472918471928374619284719',
    confidence: 0.96,
    ai_analysis_status: 'completed',
    ai_summary: 'Micro-paint spectrum matches matte obsidian coating used on commercial locksmith kit.',
    chain_of_custody: [
      { action: 'photo_logged', officer_name: 'Tech T. Ward', timestamp: '2024-06-18T05:45:00Z', facility: 'CSU Mobile Lab' }
    ]
  },
  {
    evidence_id: 'evd-005',
    case_id: 'case-003',
    case_number: 'CASE-2024-0771',
    evidence_number: 'EVD-2024-00892',
    evidence_type: 'audio',
    title: 'Intercepted Encrypted VoIP Audio Call Recording',
    description: 'Federal wiretap intercept duration 1m 42s between burner endpoint +1-555-019-4821 and Trevor Bennett.',
    source: 'Telecommunications Intercept Unit',
    collected_at: '2024-05-13T23:15:00Z',
    file_path: 's3://crimemind-vault/cases/CASE-2024-0771/voip_intercept_0892.wav',
    hash: '9182746192837461928374619283746192837461928374619283746192837461',
    confidence: 0.95,
    ai_analysis_status: 'completed',
    ai_summary: 'Voice biometric synthesis matches Evelyn Reed ("Cipher") with 94.8% acoustic resonance match.',
    chain_of_custody: [
      { action: 'warrant_tap_recorded', officer_name: 'Det. Sarah Vance', timestamp: '2024-05-13T23:15:00Z', facility: 'Telecom Vault' }
    ]
  },
  {
    evidence_id: 'evd-006',
    case_id: 'case-003',
    case_number: 'CASE-2024-0771',
    evidence_number: 'EVD-2024-00914',
    evidence_type: 'statements',
    title: 'Sworn Witness Deposition of Night Guard Arlo Higgins',
    description: 'Signed affidavit detailing suspicious power brownouts and idling dark sedan near branch loading dock.',
    source: 'Major Crimes Interview Room 3',
    collected_at: '2024-05-14T06:00:00Z',
    file_path: 's3://crimemind-vault/cases/CASE-2024-0771/deposition_higgins.pdf',
    hash: '8271625349182736451928374619283746192837461928374619283746192837',
    confidence: 0.91,
    ai_analysis_status: 'completed',
    ai_summary: 'Deposition corroborates power fluctuation timeline within 90 seconds of silent alarm trip.',
    chain_of_custody: [
      { action: 'affidavit_notarized', officer_name: 'Det. Sarah Vance', timestamp: '2024-05-14T06:00:00Z', facility: 'Central HQ' }
    ]
  },
  {
    evidence_id: 'evd-007',
    case_id: 'case-006',
    case_number: 'CASE-2024-4019',
    evidence_number: 'EVD-2024-01042',
    evidence_type: 'documents',
    title: 'Port Terminal 4 Falsified Customs Manifest',
    description: 'Forged bill of lading listing commercial air conditioners concealing 120 contraband crates.',
    source: 'Customs & Border Protection (CBP) Port Task Force',
    collected_at: '2024-08-20T10:30:00Z',
    file_path: 's3://crimemind-vault/cases/CASE-2024-4019/manifest_falsified.pdf',
    hash: '7162534891827364519283746192837461928374619283746192837461928374',
    confidence: 0.99,
    ai_analysis_status: 'flagged',
    ai_summary: 'Stamp seal matches fraudulent notary stamp documented in 2021 Operation Ironclad.',
    chain_of_custody: [
      { action: 'manifest_seized', officer_name: 'Agent R. Chen', timestamp: '2024-08-20T10:30:00Z', facility: 'Port Authority Vault' }
    ]
  },
  {
    evidence_id: 'evd-008',
    case_id: 'case-008',
    case_number: 'CASE-2023-0100',
    evidence_number: 'EVD-2023-00049',
    evidence_type: 'physical_weapons',
    title: 'Seized Diamond Core Laser Cutter Bit (Serial 88A)',
    description: 'High-temperature industrial diamond core bit seized during raid on St. Marks Place workshop.',
    source: 'Special Investigations Search Warrant #441',
    collected_at: '2024-08-28T14:00:00Z',
    file_path: 's3://crimemind-vault/cases/CASE-2023-0100/laser_bit_physical.dat',
    hash: '6152439581928374651928374619283746192837461928374619283746192837',
    confidence: 0.98,
    ai_analysis_status: 'completed',
    ai_summary: 'Tool-mark striated striations match 2023 Belvedere vault door cut grooves with 99.1% match.',
    chain_of_custody: [
      { action: 'warrant_seizure', officer_name: 'Det. Sarah Vance', timestamp: '2024-08-28T14:00:00Z', facility: 'Central Evidence Locker #12' }
    ]
  },
  {
    evidence_id: 'evd-009',
    case_id: 'case-002',
    case_number: 'CASE-2024-1100',
    evidence_number: 'EVD-2024-01188',
    evidence_type: 'call_records',
    title: 'Downtown Cell Tower Ping CDR Extract (Grand Central)',
    description: 'Bulk CDR tower dump showing 3 burner IMEIs simultaneously disconnecting prior to robbery.',
    source: 'Telecom Provider Subpoena Return',
    collected_at: '2024-05-11T09:00:00Z',
    file_path: 's3://crimemind-vault/cases/CASE-2024-1100/cdr_dump_lexington.csv',
    hash: '5142398571928374619283746192837461928374619283746192837461928374',
    confidence: 0.94,
    ai_analysis_status: 'in_progress',
    ai_summary: 'Pattern indicates coordinated pre-strike cellular silence command issued by master node.',
    chain_of_custody: [
      { action: 'subpoena_ingested', officer_name: 'Analyst K. Gomez', timestamp: '2024-05-11T09:00:00Z', facility: 'Data Forensics Vault' }
    ]
  },
  {
    evidence_id: 'evd-010',
    case_id: 'case-007',
    case_number: 'CASE-2024-8831',
    evidence_number: 'EVD-2024-01290',
    evidence_type: 'digital_files',
    title: 'Extortion Ransomware Memory Dump & Tor Onions Log',
    description: 'Volatile RAM dump from compromised municipal accounting workstation during encryption strike.',
    source: 'Cyber Response Unit Incident Triage',
    collected_at: '2024-08-26T13:20:00Z',
    file_path: 's3://crimemind-vault/cases/CASE-2024-8831/ram_triage_dump.raw',
    hash: '4132987561928374619283746192837461928374619283746192837461928374',
    confidence: 0.97,
    ai_analysis_status: 'in_progress',
    ai_summary: 'Binary command-and-control IP resolved to offshore VPN cluster associated with Cipher broker group.',
    chain_of_custody: [
      { action: 'memory_seized', officer_name: 'Tech L. Ross', timestamp: '2024-08-26T13:20:00Z', facility: 'Cybercrime Vault' }
    ]
  },
  {
    evidence_id: 'evd-011',
    case_id: 'case-005',
    case_number: 'CASE-2021-0044',
    evidence_number: 'EVD-2021-00812',
    evidence_type: 'videos',
    title: 'Convoy Interception High-Speed Pursuit Dashcam',
    description: 'State Highway Patrol dashcam recording of freight trailer interception and arrest of Viktor Orlov.',
    source: 'State Highway Patrol Division 4',
    collected_at: '2021-04-18T16:40:00Z',
    file_path: 's3://crimemind-vault/cases/CASE-2021-0044/dashcam_pursuit_orlov.mp4',
    hash: '3129847561928374619283746192837461928374619283746192837461928374',
    confidence: 1.0,
    ai_analysis_status: 'completed',
    ai_summary: 'Court-admitted prime trial exhibit resulting in conviction.',
    chain_of_custody: [
      { action: 'court_exhibit_archived', officer_name: 'Capt. Robert Chen', timestamp: '2021-11-20T17:00:00Z', facility: 'Superior Court Archives' }
    ]
  },
  {
    evidence_id: 'evd-012',
    case_id: 'case-006',
    case_number: 'CASE-2024-4019',
    evidence_number: 'EVD-2024-01305',
    evidence_type: 'cctv_records',
    title: 'Pier 42 Thermal Night Vision Surveillance Feed',
    description: 'Infrared night vision sweep documenting clandestine offloading of sealed containers at 03:15 UTC.',
    source: 'Port Security Thermal Camera CAM-PT-040',
    collected_at: '2024-08-28T03:30:00Z',
    file_path: 's3://crimemind-vault/cases/CASE-2024-4019/pier42_thermal_sweep.mp4',
    hash: '2139847561928374619283746192837461928374619283746192837461928374',
    confidence: 0.93,
    ai_analysis_status: 'completed',
    ai_summary: 'Thermal signature indicates heat dissipation matching high-speed marine outboard motors.',
    chain_of_custody: [
      { action: 'thermal_export', officer_name: 'Agent R. Chen', timestamp: '2024-08-28T04:00:00Z', facility: 'Port Authority Vault' }
    ]
  }
];

// ----------------------------------------------------------------------------
// 7B. LANGGRAPH MULTI-AGENT SWARM REGISTRY
// ----------------------------------------------------------------------------
export const initialAgentsList = [
  {
    id: 'agent-1',
    name: 'Planner Agent',
    role: 'Root Orchestrator',
    status: 'active' as const,
    currentTask: 'Orchestrating multi-modal evidence pipelines & investigative hypothesis trees',
    executionTimeMs: 180,
    confidence: 0.99,
    findingsCount: 14,
    lastExecution: new Date().toISOString(),
    errors: [],
  },
  {
    id: 'agent-2',
    name: 'Case Dossier Agent',
    role: 'Relational Intelligence',
    status: 'idle' as const,
    currentTask: 'Cross-examining open, closed, and reopened case files across jurisdictional boundaries',
    executionTimeMs: 220,
    confidence: 0.96,
    findingsCount: 18,
    lastExecution: new Date(Date.now() - 1000 * 60 * 3).toISOString(),
    errors: [],
  },
  {
    id: 'agent-3',
    name: 'Evidence Forensics Agent',
    role: 'Chain-of-Custody Validator',
    status: 'active' as const,
    currentTask: 'Validating cryptographic hashes & chain-of-custody audit signatures across all modalities',
    executionTimeMs: 310,
    confidence: 0.98,
    findingsCount: 26,
    lastExecution: new Date().toISOString(),
    errors: [],
  },
  {
    id: 'agent-4',
    name: 'Graph Topology Agent',
    role: 'Multi-Hop Correlation',
    status: 'idle' as const,
    currentTask: 'Executing 3-hop entity relationship graph traversal on Midnight Syndicate network',
    executionTimeMs: 440,
    confidence: 0.95,
    findingsCount: 22,
    lastExecution: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
    errors: [],
  },
  {
    id: 'agent-5',
    name: 'CCTV Vision Agent',
    role: 'Optical Neural Detection',
    status: 'active' as const,
    currentTask: 'Real-time optical ALPR license plate & facial recognition matches on municipal traffic feeds',
    executionTimeMs: 290,
    confidence: 0.94,
    findingsCount: 35,
    lastExecution: new Date().toISOString(),
    errors: [],
  },
  {
    id: 'agent-6',
    name: 'Person Profiler Agent',
    role: 'Entity Biometrics & Roles',
    status: 'idle' as const,
    currentTask: 'Synthesizing suspect aliases, criminal records, and cellular network connections',
    executionTimeMs: 250,
    confidence: 0.97,
    findingsCount: 19,
    lastExecution: new Date(Date.now() - 1000 * 60 * 8).toISOString(),
    errors: [],
  },
  {
    id: 'agent-7',
    name: 'Timeline Reconstruction Agent',
    role: 'Chronological Fusion',
    status: 'idle' as const,
    currentTask: 'Aligning cellular CDR tower pings, financial wire stamps, and alarm sensors chronologically',
    executionTimeMs: 330,
    confidence: 0.96,
    findingsCount: 24,
    lastExecution: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
    errors: [],
  },
  {
    id: 'agent-8',
    name: 'Law & Policy Verification Agent',
    role: 'Constitutional Compliance',
    status: 'idle' as const,
    currentTask: 'Enforcing 4th Amendment warrant constraints and evidentiary legal admissibility standards',
    executionTimeMs: 195,
    confidence: 1.0,
    findingsCount: 11,
    lastExecution: new Date(Date.now() - 1000 * 60 * 20).toISOString(),
    errors: [],
  },
  {
    id: 'agent-9',
    name: 'Synthesis Agent',
    role: 'Hypothesis Reduction',
    status: 'idle' as const,
    currentTask: 'Compiling structured, verifiable intelligence briefs with verifiable raw source citations',
    executionTimeMs: 380,
    confidence: 0.97,
    findingsCount: 31,
    lastExecution: new Date(Date.now() - 1000 * 60 * 2).toISOString(),
    errors: [],
  },
];

// ----------------------------------------------------------------------------
// 8. ALERTS
// ----------------------------------------------------------------------------
export const initialAlerts: Alert[] = [
  {
    alert_id: 'alt-001',
    title: 'Cross-Case Vehicle Match: Charger SYN-7X91',
    description: 'Vehicle SYN-7X91 observed near commercial robbery in CASE-2024-1100 matches vehicle detected in CASE-2024-1250.',
    severity: 'critical',
    alert_type: 'repeated_vehicle_appearance',
    created_at: '2024-08-29T10:15:00Z',
    source_case_id: 'case-002',
    source_case_number: 'CASE-2024-1100',
    source_evidence_title: 'CCTV Surveillance Capture - Dodge Charger',
    is_acknowledged: false,
  },
  {
    alert_id: 'alt-002',
    title: 'High-Risk Network Link: Evelyn Reed to 7 Prime Suspects',
    description: 'NetworkAnalysisAgent detected broker phone +1-555-019-4821 communicating with suspects in 5 active cases.',
    severity: 'critical',
    alert_type: 'agent_generated',
    created_at: '2024-08-29T09:30:00Z',
    source_case_id: 'case-003',
    source_case_number: 'CASE-2024-0771',
    source_evidence_title: 'Telecom CDR Intercept Analysis',
    is_acknowledged: false,
  },
  {
    alert_id: 'alt-003',
    title: 'Suspicious Pre-Strike Wire Transfer Flagged',
    description: '$25,000 incoming wire to Trevor Bennett followed by ATM cash draw within 4 miles of target vault.',
    severity: 'high',
    alert_type: 'unusual_transaction',
    created_at: '2024-08-28T22:45:00Z',
    source_case_id: 'case-003',
    source_case_number: 'CASE-2024-0771',
    source_evidence_title: '$25,000 Offshore Wire Record',
    is_acknowledged: false,
  },
  {
    alert_id: 'alt-004',
    title: 'Historical Recidivist Resurfaced: Viktor Orlov',
    description: 'Convict from closed 2021 case CASE-2021-0044 sighted at Terminal 4 48 hours prior to container theft.',
    severity: 'high',
    alert_type: 'cross_case_connection',
    created_at: '2024-08-28T18:20:00Z',
    source_case_id: 'case-004',
    source_case_number: 'CASE-2024-2390',
    source_evidence_title: 'Terminal 4 Gate CCTV Log',
    is_acknowledged: true,
  }
];

// ----------------------------------------------------------------------------
// 9. AGENT RUNS (LangGraph Orchestration)
// ----------------------------------------------------------------------------
export const initialAgentRuns: AgentRun[] = [
  {
    run_id: 'run-001',
    agent_name: 'Planner',
    task: 'Deconstruct investigation goals and spawn sub-agent orchestration tree for CASE-2024-0106',
    status: 'completed',
    started_at: '2024-08-29T10:00:00Z',
    completed_at: '2024-08-29T10:00:02Z',
    duration_ms: 1850,
    confidence: 0.98,
    output_summary: { subagents_spawned: 5, execution_mode: 'parallel_eval' },
  },
  {
    run_id: 'run-002',
    agent_name: 'NetworkAnalysisAgent',
    task: 'Recursive graph traversal on Marcus Vance (depth 3)',
    status: 'completed',
    started_at: '2024-08-29T10:00:02Z',
    completed_at: '2024-08-29T10:00:07Z',
    duration_ms: 4620,
    confidence: 0.95,
    output_summary: { associates_uncovered: 14, syndicates_mapped: 1 },
  },
  {
    run_id: 'run-003',
    agent_name: 'CrossCaseMatcherAgent',
    task: 'Correlate vehicle movements across commercial robberies',
    status: 'completed',
    started_at: '2024-08-29T10:00:02Z',
    completed_at: '2024-08-29T10:00:05Z',
    duration_ms: 3100,
    confidence: 0.94,
    output_summary: { target_identified: 'SYN-7X91', linked_cases: 4 },
  },
  {
    run_id: 'run-004',
    agent_name: 'TimelineReconstructionAgent',
    task: 'Synthesize First National Bank vault ingress timeline',
    status: 'completed',
    started_at: '2024-08-29T10:00:05Z',
    completed_at: '2024-08-29T10:00:09Z',
    duration_ms: 3840,
    confidence: 0.96,
    output_summary: { temporal_events_synchronized: 38, gaps_detected: 0 },
  },
  {
    run_id: 'run-005',
    agent_name: 'EvidenceSynthesizerAgent',
    task: 'Cluster optical laser tool marks across 8 estate burglaries',
    status: 'completed',
    started_at: '2024-08-29T10:00:09Z',
    completed_at: '2024-08-29T10:00:13Z',
    duration_ms: 4120,
    confidence: 0.97,
    output_summary: { identical_mo_verified: true, suspect_signature: 'Julian_Drake_Locksmith' },
  }
];

// ----------------------------------------------------------------------------
// 10. AI FINDINGS
// ----------------------------------------------------------------------------
export const initialAIFindings: AIFinding[] = [
  {
    finding_id: 'find-001',
    case_id: 'case-001',
    agent_name: 'NetworkAnalysisAgent',
    finding_type: 'network_anomaly',
    title: 'The Midnight Syndicate Fencing Ring Uncovered',
    finding_text: 'High-confidence correlation links Marcus Vance (Pawn King) as master fencer for Julian Drake (Locksmith). Financial proceeds laundered via cash-equivalent buyouts within 48 hours of each burglary.',
    confidence: 0.965,
    supporting_evidence_ids: ['evd-001'],
    supporting_entity_references: [
      { type: 'PERSON', id: 'per-001', name: 'Marcus Vance' },
      { type: 'PERSON', id: 'per-002', name: 'Julian Drake' }
    ],
    human_verified: true,
    verified_by: 'Det. Sarah Vance',
    verified_at: '2024-08-28T14:30:00Z',
    verification_notes: 'Confirmed by bank statement subpoenas and wire receipts.',
    created_at: '2024-08-28T11:00:00Z',
  },
  {
    finding_id: 'find-002',
    case_id: 'case-002',
    agent_name: 'CrossCaseMatcherAgent',
    finding_type: 'cross_case_match',
    title: 'Getaway Vehicle SYN-7X91 Linked to 4 Robberies',
    finding_text: 'Automated optical character recognition (OCR) and speed vector analysis establishes Dodge Charger SYN-7X91 registered to Damian Cross as primary getaway conveyance.',
    confidence: 0.942,
    supporting_evidence_ids: ['evd-002'],
    supporting_entity_references: [
      { type: 'VEHICLE', id: 'veh-001', name: 'Dodge Charger SYN-7X91' },
      { type: 'PERSON', id: 'per-003', name: 'Damian Cross' }
    ],
    human_verified: false,
    created_at: '2024-08-29T08:15:00Z',
  },
  {
    finding_id: 'find-003',
    case_id: 'case-003',
    agent_name: 'TimelineReconstructionAgent',
    finding_type: 'timeline_inconsistency',
    title: 'Pre-Strike Funding to Vault Presence Within 3 Hours',
    finding_text: 'Wire of $25,000 from offshore escrow followed by cell tower ping and CCTV face identification of Trevor Bennett outside First National Bank 45 mins prior to alarm.',
    confidence: 0.978,
    supporting_evidence_ids: ['evd-003'],
    supporting_entity_references: [
      { type: 'PERSON', id: 'per-005', name: 'Trevor Bennett' },
      { type: 'LOCATION', id: 'loc-001', name: 'First National Bank & Vault' }
    ],
    human_verified: false,
    created_at: '2024-08-29T09:45:00Z',
  }
];

// ----------------------------------------------------------------------------
// 11. GRAPH DATA (Nodes & Edges)
// ----------------------------------------------------------------------------
export const initialGraphData: GraphData = {
  nodes: [
    { id: 'per-001', label: 'Marcus "Viper" Vance', type: 'PERSON', subType: 'Kingpin / Fencer', riskLevel: 'extreme', confidence: 0.98, x: 420, y: 220, size: 26 },
    { id: 'per-002', label: 'Julian "Ghost" Drake', type: 'PERSON', subType: 'Locksmith / Breaker', riskLevel: 'high', confidence: 0.96, x: 260, y: 180, size: 24 },
    { id: 'per-003', label: 'Damian Cross', type: 'PERSON', subType: 'Getaway Driver', riskLevel: 'high', confidence: 0.94, x: 780, y: 220, size: 24 },
    { id: 'per-004', label: 'Evelyn "Cipher" Reed', type: 'PERSON', subType: 'Clandestine Broker', riskLevel: 'extreme', confidence: 0.97, x: 600, y: 350, size: 28 },
    { id: 'per-005', label: 'Trevor "Spike" Bennett', type: 'PERSON', subType: 'Safe Operative', riskLevel: 'high', confidence: 0.95, x: 500, y: 500, size: 24 },
    { id: 'per-006', label: 'Viktor "Old Fox" Orlov', type: 'PERSON', subType: 'Freight Smuggler', riskLevel: 'extreme', confidence: 0.98, x: 740, y: 480, size: 26 },

    { id: 'case-001', label: 'Belvedere Burglary #7', type: 'CASE', subType: 'Aggravated Burglary', riskLevel: 'high', x: 220, y: 320, size: 28 },
    { id: 'case-002', label: 'Jewelry Exchange Robbery', type: 'CASE', subType: 'Commercial Robbery', riskLevel: 'critical', x: 920, y: 260, size: 28 },
    { id: 'case-003', label: 'First National Vault Infiltration', type: 'CASE', subType: 'Armed Bank Robbery', riskLevel: 'critical', x: 380, y: 560, size: 30 },
    { id: 'case-004', label: 'Terminal 4 Container Diversion', type: 'CASE', subType: 'Organized Cargo Theft', riskLevel: 'high', x: 880, y: 460, size: 26 },
    { id: 'case-005', label: 'Operation Ironclad (2021)', type: 'CASE', subType: 'Historical Conviction', riskLevel: 'medium', x: 920, y: 600, size: 24 },

    { id: 'veh-001', label: 'Dodge Charger (SYN-7X91)', type: 'VEHICLE', subType: 'Dark Gray Sedan', riskLevel: 'high', x: 850, y: 130, size: 22 },
    { id: 'veh-002', label: 'Ford Explorer (SYN-4K82)', type: 'VEHICLE', subType: 'Black SUV', riskLevel: 'high', x: 860, y: 540, size: 22 },

    { id: 'loc-001', label: 'First National Bank', type: 'LOCATION', subType: 'atm_bank', riskLevel: 'critical', x: 260, y: 560, size: 22 },
    { id: 'loc-002', label: 'Terminal 4 Port', type: 'LOCATION', subType: 'port_marina', riskLevel: 'high', x: 960, y: 400, size: 22 },
    { id: 'loc-003', label: 'Belvedere Estates', type: 'LOCATION', subType: 'residential', riskLevel: 'high', x: 100, y: 320, size: 22 },
    { id: 'loc-004', label: 'Jewelry Exchange', type: 'LOCATION', subType: 'commercial', riskLevel: 'high', x: 1020, y: 220, size: 22 },

    { id: 'evd-001', label: 'Laser Cut Lead Fragments', type: 'EVIDENCE', subType: 'forensic_records', x: 140, y: 220, size: 20 },
    { id: 'evd-002', label: 'CCTV Charger Sighting', type: 'EVIDENCE', subType: 'cctv_records', x: 980, y: 120, size: 20 },
    { id: 'evd-003', label: '$25,000 Offshore Wire Record', type: 'EVIDENCE', subType: 'transaction_records', x: 480, y: 640, size: 20 }
  ],
  edges: [
    // Scenario 1
    { id: 'e-1', source: 'per-001', target: 'per-002', relationshipType: 'KNOWN_ASSOCIATE', relationship: 'KNOWN_ASSOCIATE', label: 'Syndicate Partners', confidence: 0.98 },
    { id: 'e-2', source: 'per-001', target: 'case-001', relationshipType: 'LINKED_TO_CASE', relationship: 'LINKED_TO_CASE', label: 'Primary Suspect', confidence: 0.96 },
    { id: 'e-3', source: 'per-002', target: 'case-001', relationshipType: 'LINKED_TO_CASE', relationship: 'LINKED_TO_CASE', label: 'Locksmith Suspect', confidence: 0.95 },
    { id: 'e-4', source: 'case-001', target: 'loc-003', relationshipType: 'LOCATED_AT', relationship: 'LOCATED_AT', label: 'Crime Scene', confidence: 1.0 },
    { id: 'e-5', source: 'evd-001', target: 'case-001', relationshipType: 'EVIDENCE_SUPPORTS', relationship: 'EVIDENCE_SUPPORTS', label: 'Forensic Match', confidence: 0.97 },

    // Scenario 2
    { id: 'e-6', source: 'per-003', target: 'veh-001', relationshipType: 'OWNS', relationship: 'OWNS', label: 'Registered Owner', confidence: 1.0 },
    { id: 'e-7', source: 'veh-001', target: 'case-002', relationshipType: 'VEHICLE_APPEARANCE', relationship: 'VEHICLE_APPEARANCE', label: 'Getaway Vehicle', confidence: 0.94 },
    { id: 'e-8', source: 'case-002', target: 'loc-004', relationshipType: 'LOCATED_AT', relationship: 'LOCATED_AT', label: 'Crime Scene', confidence: 1.0 },
    { id: 'e-9', source: 'evd-002', target: 'veh-001', relationshipType: 'EVIDENCE_SUPPORTS', relationship: 'EVIDENCE_SUPPORTS', label: 'Plate Match', confidence: 0.95 },

    // Scenario 3 (Evelyn Reed Nexus)
    { id: 'e-10', source: 'per-004', target: 'per-001', relationshipType: 'COMMUNICATION', relationship: 'COMMUNICATION', label: 'Encrypted VoIP', confidence: 0.94 },
    { id: 'e-11', source: 'per-004', target: 'per-003', relationshipType: 'COMMUNICATION', relationship: 'COMMUNICATION', label: 'Encrypted VoIP', confidence: 0.92 },
    { id: 'e-12', source: 'per-004', target: 'per-005', relationshipType: 'COMMUNICATION', relationship: 'COMMUNICATION', label: 'Encrypted VoIP', confidence: 0.95 },
    { id: 'e-13', source: 'per-004', target: 'per-006', relationshipType: 'COMMUNICATION', relationship: 'COMMUNICATION', label: 'Encrypted VoIP', confidence: 0.93 },

    // Scenario 4
    { id: 'e-14', source: 'per-004', target: 'per-005', relationshipType: 'TRANSACTION', relationship: 'TRANSACTION', label: '$25,000 Wire', confidence: 1.0 },
    { id: 'e-15', source: 'per-005', target: 'loc-001', relationshipType: 'SEEN_WITH', relationship: 'SEEN_WITH', label: 'CCTV Sighting', confidence: 0.98 },
    { id: 'e-16', source: 'per-005', target: 'case-003', relationshipType: 'LINKED_TO_CASE', relationship: 'LINKED_TO_CASE', label: 'Suspect in Vault Breach', confidence: 0.96 },
    { id: 'e-17', source: 'evd-003', target: 'case-003', relationshipType: 'EVIDENCE_SUPPORTS', relationship: 'EVIDENCE_SUPPORTS', label: 'Funding Proof', confidence: 1.0 },

    // Scenario 5
    { id: 'e-18', source: 'per-006', target: 'case-005', relationshipType: 'LINKED_TO_CASE', relationship: 'LINKED_TO_CASE', label: '2021 Conviction', confidence: 1.0 },
    { id: 'e-19', source: 'per-006', target: 'case-004', relationshipType: 'LINKED_TO_CASE', relationship: 'LINKED_TO_CASE', label: '2024 Resurfaced Suspect', confidence: 0.92 },
    { id: 'e-20', source: 'per-006', target: 'veh-002', relationshipType: 'OWNS', relationship: 'OWNS', label: 'Registered SUV', confidence: 1.0 },
    { id: 'e-21', source: 'veh-002', target: 'loc-002', relationshipType: 'VEHICLE_APPEARANCE', relationship: 'VEHICLE_APPEARANCE', label: 'Terminal Sighting', confidence: 0.98 }
  ]
};
